
#include <gint/display.h>

struct image {
  int xOffset;
  int yOffset;
  const bopti_image_t *data;
};
extern const bopti_image_t b_kart_0;
const struct image internal_img_kart_0 = { 13, 13, &b_kart_0 };
const struct image* img_kart_0 = &internal_img_kart_0;
extern const bopti_image_t b_kart_1;
const struct image internal_img_kart_1 = { 14, 13, &b_kart_1 };
const struct image* img_kart_1 = &internal_img_kart_1;
extern const bopti_image_t b_kart_2;
const struct image internal_img_kart_2 = { 15, 13, &b_kart_2 };
const struct image* img_kart_2 = &internal_img_kart_2;
extern const bopti_image_t b_kart_3;
const struct image internal_img_kart_3 = { 16, 14, &b_kart_3 };
const struct image* img_kart_3 = &internal_img_kart_3;
extern const bopti_image_t b_kart_4;
const struct image internal_img_kart_4 = { 17, 15, &b_kart_4 };
const struct image* img_kart_4 = &internal_img_kart_4;
extern const bopti_image_t b_kart_5;
const struct image internal_img_kart_5 = { 15, 16, &b_kart_5 };
const struct image* img_kart_5 = &internal_img_kart_5;
extern const bopti_image_t b_kart_6;
const struct image internal_img_kart_6 = { 14, 17, &b_kart_6 };
const struct image* img_kart_6 = &internal_img_kart_6;
extern const bopti_image_t b_kart_7;
const struct image internal_img_kart_7 = { 13, 18, &b_kart_7 };
const struct image* img_kart_7 = &internal_img_kart_7;
extern const bopti_image_t b_kart_8;
const struct image internal_img_kart_8 = { 11, 18, &b_kart_8 };
const struct image* img_kart_8 = &internal_img_kart_8;
extern const bopti_image_t b_kart_9;
const struct image internal_img_kart_9 = { 10, 17, &b_kart_9 };
const struct image* img_kart_9 = &internal_img_kart_9;
extern const bopti_image_t b_kart_10;
const struct image internal_img_kart_10 = { 9, 16, &b_kart_10 };
const struct image* img_kart_10 = &internal_img_kart_10;
extern const bopti_image_t b_kart_11;
const struct image internal_img_kart_11 = { 12, 64, &b_kart_11 };
const struct image* img_kart_11 = &internal_img_kart_11;
extern const bopti_image_t b_kart_12;
const struct image internal_img_kart_12 = { 14, 65, &b_kart_12 };
const struct image* img_kart_12 = &internal_img_kart_12;
extern const bopti_image_t b_kart_13;
const struct image internal_img_kart_13 = { 15, 65, &b_kart_13 };
const struct image* img_kart_13 = &internal_img_kart_13;
extern const bopti_image_t b_kart_14;
const struct image internal_img_kart_14 = { 16, 65, &b_kart_14 };
const struct image* img_kart_14 = &internal_img_kart_14;
extern const bopti_image_t b_kart_15;
const struct image internal_img_kart_15 = { 17, 65, &b_kart_15 };
const struct image* img_kart_15 = &internal_img_kart_15;
extern const bopti_image_t b_kart_16;
const struct image internal_img_kart_16 = { 15, 65, &b_kart_16 };
const struct image* img_kart_16 = &internal_img_kart_16;
extern const bopti_image_t b_kart_17;
const struct image internal_img_kart_17 = { 14, 65, &b_kart_17 };
const struct image* img_kart_17 = &internal_img_kart_17;
extern const bopti_image_t b_kart_18;
const struct image internal_img_kart_18 = { 13, 65, &b_kart_18 };
const struct image* img_kart_18 = &internal_img_kart_18;
extern const bopti_image_t b_kart_19;
const struct image internal_img_kart_19 = { 11, 65, &b_kart_19 };
const struct image* img_kart_19 = &internal_img_kart_19;
extern const bopti_image_t b_kart_20;
const struct image internal_img_kart_20 = { 10, 65, &b_kart_20 };
const struct image* img_kart_20 = &internal_img_kart_20;
extern const bopti_image_t b_kart_21;
const struct image internal_img_kart_21 = { 9, 64, &b_kart_21 };
const struct image* img_kart_21 = &internal_img_kart_21;
const struct image* imgs_kart[22] = {  &internal_img_kart_0,   &internal_img_kart_1,   &internal_img_kart_2,   &internal_img_kart_3,   &internal_img_kart_4,   &internal_img_kart_5,   &internal_img_kart_6,   &internal_img_kart_7,   &internal_img_kart_8,   &internal_img_kart_9,   &internal_img_kart_10,   &internal_img_kart_11,   &internal_img_kart_12,   &internal_img_kart_13,   &internal_img_kart_14,   &internal_img_kart_15,   &internal_img_kart_16,   &internal_img_kart_17,   &internal_img_kart_18,   &internal_img_kart_19,   &internal_img_kart_20,   &internal_img_kart_21, };
extern const bopti_image_t b_castle;
const struct image internal_img_castle = { 0, 11, &b_castle };
const struct image* img_castle = &internal_img_castle;
extern const bopti_image_t b_bush;
const struct image internal_img_bush = { 0, 0, &b_bush };
const struct image* img_bush = &internal_img_bush;
extern const bopti_image_t b_shadow1;
const struct image internal_img_shadow1 = { 14, 70, &b_shadow1 };
const struct image* img_shadow1 = &internal_img_shadow1;
extern const bopti_image_t b_shadow2;
const struct image internal_img_shadow2 = { 14, 70, &b_shadow2 };
const struct image* img_shadow2 = &internal_img_shadow2;
extern const bopti_image_t b_smoke_0;
const struct image internal_img_smoke_0 = { 4, 4, &b_smoke_0 };
const struct image* img_smoke_0 = &internal_img_smoke_0;
extern const bopti_image_t b_smoke_1;
const struct image internal_img_smoke_1 = { 1, 1, &b_smoke_1 };
const struct image* img_smoke_1 = &internal_img_smoke_1;
extern const bopti_image_t b_smoke_2;
const struct image internal_img_smoke_2 = { 0, 0, &b_smoke_2 };
const struct image* img_smoke_2 = &internal_img_smoke_2;
const struct image* imgs_smoke[3] = {  &internal_img_smoke_0,   &internal_img_smoke_1,   &internal_img_smoke_2, };
extern const bopti_image_t b_boost_0;
const struct image internal_img_boost_0 = { 12, 8, &b_boost_0 };
const struct image* img_boost_0 = &internal_img_boost_0;
extern const bopti_image_t b_boost_1;
const struct image internal_img_boost_1 = { 14, 9, &b_boost_1 };
const struct image* img_boost_1 = &internal_img_boost_1;
extern const bopti_image_t b_boost_2;
const struct image internal_img_boost_2 = { 8, 5, &b_boost_2 };
const struct image* img_boost_2 = &internal_img_boost_2;
extern const bopti_image_t b_boost_3;
const struct image internal_img_boost_3 = { 3, 1, &b_boost_3 };
const struct image* img_boost_3 = &internal_img_boost_3;
extern const bopti_image_t b_boost_4;
const struct image internal_img_boost_4 = { 0, 0, &b_boost_4 };
const struct image* img_boost_4 = &internal_img_boost_4;
const struct image* imgs_boost[5] = {  &internal_img_boost_0,   &internal_img_boost_1,   &internal_img_boost_2,   &internal_img_boost_3,   &internal_img_boost_4, };
extern const bopti_image_t b_font_0;
const struct image internal_img_font_0 = { 0, 1, &b_font_0 };
const struct image* img_font_0 = &internal_img_font_0;
extern const bopti_image_t b_font_1;
const struct image internal_img_font_1 = { 0, 1, &b_font_1 };
const struct image* img_font_1 = &internal_img_font_1;
extern const bopti_image_t b_font_2;
const struct image internal_img_font_2 = { 0, 1, &b_font_2 };
const struct image* img_font_2 = &internal_img_font_2;
extern const bopti_image_t b_font_3;
const struct image internal_img_font_3 = { 0, 1, &b_font_3 };
const struct image* img_font_3 = &internal_img_font_3;
extern const bopti_image_t b_font_4;
const struct image internal_img_font_4 = { 0, 1, &b_font_4 };
const struct image* img_font_4 = &internal_img_font_4;
extern const bopti_image_t b_font_5;
const struct image internal_img_font_5 = { 0, 1, &b_font_5 };
const struct image* img_font_5 = &internal_img_font_5;
extern const bopti_image_t b_font_6;
const struct image internal_img_font_6 = { 0, 1, &b_font_6 };
const struct image* img_font_6 = &internal_img_font_6;
extern const bopti_image_t b_font_7;
const struct image internal_img_font_7 = { 0, 1, &b_font_7 };
const struct image* img_font_7 = &internal_img_font_7;
extern const bopti_image_t b_font_8;
const struct image internal_img_font_8 = { 0, 1, &b_font_8 };
const struct image* img_font_8 = &internal_img_font_8;
extern const bopti_image_t b_font_9;
const struct image internal_img_font_9 = { 0, 1, &b_font_9 };
const struct image* img_font_9 = &internal_img_font_9;
extern const bopti_image_t b_font_10;
const struct image internal_img_font_10 = { 0, 3, &b_font_10 };
const struct image* img_font_10 = &internal_img_font_10;
const struct image* imgs_font[11] = {  &internal_img_font_0,   &internal_img_font_1,   &internal_img_font_2,   &internal_img_font_3,   &internal_img_font_4,   &internal_img_font_5,   &internal_img_font_6,   &internal_img_font_7,   &internal_img_font_8,   &internal_img_font_9,   &internal_img_font_10, };
extern const bopti_image_t b_countdown_0;
const struct image internal_img_countdown_0 = { 0, 0, &b_countdown_0 };
const struct image* img_countdown_0 = &internal_img_countdown_0;
extern const bopti_image_t b_countdown_1;
const struct image internal_img_countdown_1 = { 54, 0, &b_countdown_1 };
const struct image* img_countdown_1 = &internal_img_countdown_1;
extern const bopti_image_t b_countdown_2;
const struct image internal_img_countdown_2 = { 48, 1, &b_countdown_2 };
const struct image* img_countdown_2 = &internal_img_countdown_2;
extern const bopti_image_t b_countdown_3;
const struct image internal_img_countdown_3 = { 47, 0, &b_countdown_3 };
const struct image* img_countdown_3 = &internal_img_countdown_3;
const struct image* imgs_countdown[4] = {  &internal_img_countdown_0,   &internal_img_countdown_1,   &internal_img_countdown_2,   &internal_img_countdown_3, };
extern const bopti_image_t b_fire_0;
const struct image internal_img_fire_0 = { 0, 0, &b_fire_0 };
const struct image* img_fire_0 = &internal_img_fire_0;
extern const bopti_image_t b_fire_1;
const struct image internal_img_fire_1 = { 0, 0, &b_fire_1 };
const struct image* img_fire_1 = &internal_img_fire_1;
extern const bopti_image_t b_fire_2;
const struct image internal_img_fire_2 = { 0, 0, &b_fire_2 };
const struct image* img_fire_2 = &internal_img_fire_2;
const struct image* imgs_fire[3] = {  &internal_img_fire_0,   &internal_img_fire_1,   &internal_img_fire_2, };
extern const bopti_image_t b_smallboost_0;
const struct image internal_img_smallboost_0 = { 21, 18, &b_smallboost_0 };
const struct image* img_smallboost_0 = &internal_img_smallboost_0;
extern const bopti_image_t b_smallboost_1;
const struct image internal_img_smallboost_1 = { 12, 8, &b_smallboost_1 };
const struct image* img_smallboost_1 = &internal_img_smallboost_1;
extern const bopti_image_t b_smallboost_2;
const struct image internal_img_smallboost_2 = { 14, 9, &b_smallboost_2 };
const struct image* img_smallboost_2 = &internal_img_smallboost_2;
extern const bopti_image_t b_smallboost_3;
const struct image internal_img_smallboost_3 = { 8, 5, &b_smallboost_3 };
const struct image* img_smallboost_3 = &internal_img_smallboost_3;
extern const bopti_image_t b_smallboost_4;
const struct image internal_img_smallboost_4 = { 0, 1, &b_smallboost_4 };
const struct image* img_smallboost_4 = &internal_img_smallboost_4;
const struct image* imgs_smallboost[5] = {  &internal_img_smallboost_0,   &internal_img_smallboost_1,   &internal_img_smallboost_2,   &internal_img_smallboost_3,   &internal_img_smallboost_4, };
extern const bopti_image_t b_lap_0;
const struct image internal_img_lap_0 = { 0, 0, &b_lap_0 };
const struct image* img_lap_0 = &internal_img_lap_0;
extern const bopti_image_t b_lap_1;
const struct image internal_img_lap_1 = { 0, 0, &b_lap_1 };
const struct image* img_lap_1 = &internal_img_lap_1;
extern const bopti_image_t b_lap_2;
const struct image internal_img_lap_2 = { 0, 0, &b_lap_2 };
const struct image* img_lap_2 = &internal_img_lap_2;
const struct image* imgs_lap[3] = {  &internal_img_lap_0,   &internal_img_lap_1,   &internal_img_lap_2, };
extern const bopti_image_t b_bg_dither;
const struct image internal_img_bg_dither = { 0, 0, &b_bg_dither };
const struct image* img_bg_dither = &internal_img_bg_dither;
extern const bopti_image_t b_loop_old;
const struct image internal_img_loop_old = { 0, 0, &b_loop_old };
const struct image* img_loop_old = &internal_img_loop_old;
extern const bopti_image_t b_loop;
const struct image internal_img_loop = { 0, 0, &b_loop };
const struct image* img_loop = &internal_img_loop;
extern const bopti_image_t b_bg_sunset;
const struct image internal_img_bg_sunset = { 0, 0, &b_bg_sunset };
const struct image* img_bg_sunset = &internal_img_bg_sunset;
extern const bopti_image_t b_bg;
const struct image internal_img_bg = { 0, 0, &b_bg };
const struct image* img_bg = &internal_img_bg;
extern const bopti_image_t b_skygarden_bg;
const struct image internal_img_skygarden_bg = { 0, 0, &b_skygarden_bg };
const struct image* img_skygarden_bg = &internal_img_skygarden_bg;
extern const bopti_image_t b_skygarden_bg2;
const struct image internal_img_skygarden_bg2 = { 0, 0, &b_skygarden_bg2 };
const struct image* img_skygarden_bg2 = &internal_img_skygarden_bg2;
extern const bopti_image_t b_tree;
const struct image internal_img_tree = { 0, 0, &b_tree };
const struct image* img_tree = &internal_img_tree;
